### PR TITLE
Feat/alert presenter

### PR DESCRIPTION
**Pull request by sheikhbayazid**
- Fixed file header name from ShortcutFoundation to ShortcutSwiftUI
 
**Feature** - **Alert Presenter**
Using this alert presenter removes the conflicts for SwiftUI alerts in SwiftUI views. 
It has support for both alert and action sheet.

_Types of Alert options_:
```
 titleAndDismiss -  Title and dismiss button
 titleMessageAndDismiss - Title, Message and Dismiss button
 titleAndTwoButton - Title, Primary and Secondary buttons
 titleMessageAndTwoButton - Title, Message, Primary and Secondary buttons
```

_How to use in the view_: 
```
struct ExampleView: View {
    @InjectObject private var alertPresenter: AlertPresenter
    
    var body: some View {
        VStack {
            Text("Hello World!")
        }
        .alert(item: $alertPresenter.alertPresentationState, content: alertPresenter.alertContent(for:))
        .actionSheet(item: $alertPresenter.actionSheetPresentationState, content: alertPresenter.actionSheetContent(for:))
    }
    
    // If you use modal presenter add these in the modalContent view too
    
    @ViewBuilder
    private func modalContent(for state: ModalPresentationState) -> some View {
        Group {
            switch state {
            case .test:
                TextView()
            }
        }
        .alert(item: $alertPresenter.alertPresentationState, content: alertPresenter.alertContent(for:))
        .actionSheet(item: $alertPresenter.actionSheetPresentationState, content: alertPresenter.actionSheetContent(for:))
    }
}
```

_How to present an alert_:
```
final class ExampleViewModel {
    @Inject private var alertPresenter: IAlertPresenter
    
    func presentTestAlert() {
        // For alert
        alertPresenter.setAlert(state: .titleAndDismiss("Test", "Dismiss"), type: .alert)
        
        // for action sheet
        alertPresenter.setAlert(state: .titleAndDismiss("Test", "Dismiss"), type: .actionSheet)
    }
}
```

### CODE REVIEW

**Review by lemonandlime — COMMENTED** [review]
Looks very good. Great idea. But I think that you havent ran this in your code yet right? You will need a lot of added `public` prefixes on classes, protocols and variables. 

Lets try to use your branch as a package and se what changes you have to do.

**Comment by kumarswathi** [comment]
I like the idea, but I think the layering and exposing methods to the base code could be a bit different. Like Karl suggested, it is best to use it in the current project, refactor and then merge it to the package.

**Comment by sheikhbayazid** [comment]
Thanks @lemonandlime and @swathikumar-shortcut!
Now I made them public and tried in project, it worked.

Screenshot 2022-03-23 at 3 13 23 PM

**Review by gabrielPeart — APPROVED** [review]

**Comment by gabrielPeart** [comment]
@lemonandlime @swathikumar-shortcut 

Let's get it merged

**Review by nssina — APPROVED** [review]

**Pull request merged**
